---
version: "3"
services:
  service_gamma:
    build:
      context: "../generic-service"
      dockerfile: Dockerfile.service
      args:
        SERVICE_CONTAINER_PORT: "50053"
    container_name: service_gamma
    ports:
      - "59999:50053"
    environment:
      SERVICE_NAME: service_gamma
      SERVICE_PORT: "50053"
      CONFIG_PATH: /app/config.json
    volumes:
      - "./service_configs/service_gamma_config.json:/app/config.json"
    networks:
      - microservice_net
  service_epsilon:
    build:
      context: "../generic-service"
      dockerfile: Dockerfile.service
      args:
        SERVICE_CONTAINER_PORT: "50055"
    container_name: service_epsilon
    ports:
      - "59998:50055"
    environment:
      SERVICE_NAME: service_epsilon
      SERVICE_PORT: "50055"
      CONFIG_PATH: /app/config.json
    volumes:
      - "./service_configs/service_epsilon_config.json:/app/config.json"
    networks:
      - microservice_net
  service_beta:
    build:
      context: "../generic-service"
      dockerfile: Dockerfile.service
      args:
        SERVICE_CONTAINER_PORT: "50052"
    container_name: service_beta
    ports:
      - "59997:50052"
    environment:
      SERVICE_NAME: service_beta
      SERVICE_PORT: "50052"
      CONFIG_PATH: /app/config.json
    volumes:
      - "./service_configs/service_beta_config.json:/app/config.json"
    networks:
      - microservice_net
  service_alpha:
    build:
      context: "../generic-service"
      dockerfile: Dockerfile.service
      args:
        SERVICE_CONTAINER_PORT: "50051"
    container_name: service_alpha
    ports:
      - "59996:50051"
    environment:
      SERVICE_NAME: service_alpha
      SERVICE_PORT: "50051"
      CONFIG_PATH: /app/config.json
    volumes:
      - "./service_configs/service_alpha_config.json:/app/config.json"
    networks:
      - microservice_net
  service_delta:
    build:
      context: "../generic-service"
      dockerfile: Dockerfile.service
      args:
        SERVICE_CONTAINER_PORT: "50054"
    container_name: service_delta
    ports:
      - "59995:50054"
    environment:
      SERVICE_NAME: service_delta
      SERVICE_PORT: "50054"
      CONFIG_PATH: /app/config.json
    volumes:
      - "./service_configs/service_delta_config.json:/app/config.json"
    networks:
      - microservice_net
networks:
  microservice_net:
    driver: bridge